#
# linux/drivers/nand/Makefile
#

obj-$(CONFIG_MTD_NAND)			+= nand.o
obj-$(CONFIG_MTD_NAND_ECC)		+= nand_ecc.o
obj-$(CONFIG_MTD_NAND_BCH)		+= nand_bch.o
obj-$(CONFIG_MTD_NAND_IDS)		+= nand_ids.o
obj-$(CONFIG_MTD_SM_COMMON) 	+= sm_common.o

obj-$(CONFIG_MTD_NAND_CAFE)		+= cafe_nand.o
obj-$(CONFIG_MTD_NAND_AMS_DELTA)	+= ams-delta.o
obj-$(CONFIG_MTD_NAND_DENALI)		+= denali.o
obj-$(CONFIG_MTD_NAND_DENALI_PCI)	+= denali_pci.o
obj-$(CONFIG_MTD_NAND_DENALI_DT)	+= denali_dt.o
obj-$(CONFIG_MTD_NAND_AU1550)		+= au1550nd.o
obj-$(CONFIG_MTD_NAND_BF5XX)		+= bf5xx_nand.o
obj-$(CONFIG_MTD_NAND_S3C2410)		+= s3c2410.o
obj-$(CONFIG_MTD_NAND_DAVINCI)		+= davinci_nand.o
obj-$(CONFIG_MTD_NAND_DISKONCHIP)	+= diskonchip.o
obj-$(CONFIG_MTD_NAND_DOCG4)		+= docg4.o
obj-$(CONFIG_MTD_NAND_FSMC)		+= fsmc_nand.o
obj-$(CONFIG_MTD_NAND_SHARPSL)		+= sharpsl.o
obj-$(CONFIG_MTD_NAND_NANDSIM)		+= nandsim.o
obj-$(CONFIG_MTD_NAND_CS553X)		+= cs553x_nand.o
obj-$(CONFIG_MTD_NAND_NDFC)		+= ndfc.o
obj-$(CONFIG_MTD_NAND_ATMEL)		+= atmel_nand.o
obj-$(CONFIG_MTD_NAND_GPIO)		+= gpio.o
obj-$(CONFIG_MTD_NAND_OMAP2) 		+= omap2.o
obj-$(CONFIG_MTD_NAND_CM_X270)		+= cmx270_nand.o
obj-$(CONFIG_MTD_NAND_PXA3xx)		+= pxa3xx_nand.o
obj-$(CONFIG_MTD_NAND_TMIO)		+= tmio_nand.o
obj-$(CONFIG_MTD_NAND_PLATFORM)		+= plat_nand.o
obj-$(CONFIG_MTD_ALAUDA)		+= alauda.o
obj-$(CONFIG_MTD_NAND_PASEMI)		+= pasemi_nand.o
obj-$(CONFIG_MTD_NAND_ORION)		+= orion_nand.o
obj-$(CONFIG_MTD_NAND_FSL_ELBC)		+= fsl_elbc_nand.o
obj-$(CONFIG_MTD_NAND_FSL_IFC)		+= fsl_ifc_nand.o
obj-$(CONFIG_MTD_NAND_FSL_UPM)		+= fsl_upm.o
obj-$(CONFIG_MTD_NAND_SLC_LPC32XX)      += lpc32xx_slc.o
obj-$(CONFIG_MTD_NAND_MLC_LPC32XX)      += lpc32xx_mlc.o
obj-$(CONFIG_MTD_NAND_SH_FLCTL)		+= sh_flctl.o
obj-$(CONFIG_MTD_NAND_MXC)		+= mxc_nand.o
obj-$(CONFIG_MTD_NAND_SOCRATES)		+= socrates_nand.o
obj-$(CONFIG_MTD_NAND_TXX9NDFMC)	+= txx9ndfmc.o
obj-$(CONFIG_MTD_NAND_NUC900)		+= nuc900_nand.o
obj-$(CONFIG_MTD_NAND_MPC5121_NFC)	+= mpc5121_nfc.o
obj-$(CONFIG_MTD_NAND_RICOH)		+= r852.o
obj-$(CONFIG_MTD_NAND_JZ4740)		+= jz4740_nand.o
obj-$(CONFIG_MTD_NAND_GPMI_NAND)	+= gpmi-nand/
obj-$(CONFIG_MTD_NAND_XWAY)		+= xway_nand.o
obj-$(CONFIG_MTD_NAND_BCM47XXNFLASH)	+= bcm47xxnflash/


#if we use nand common driver
#obj-$(CONFIG_MTD_NAND_MT5368)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5389)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5396)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5398)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5880)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5881)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5399)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5890)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5891)		+= mtk_nand_cm.o mtdsdm.o
#obj-$(CONFIG_MTD_NAND_MT5861)		+= mtk_nand_cm.o mtdsdm.o

#obj-$(CONFIG_MTD_NAND_MT5368)		+= nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5389)		+= nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5396)		+= nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5398)		+= nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5399)		+= nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5880)		+= nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5881)		+= nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5890)   += nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5891)   += nfi_common_hal.o
#obj-$(CONFIG_MTD_NAND_MT5861)   += nfi_common_hal.o

#obj-$(CONFIG_MTD_NAND_MT5368)		+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5389)		+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5396)		+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5398)		+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5399)		+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5880)		+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5881)		+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5890)   	+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5891)   	+= nand_vfy_driver.o
#obj-$(CONFIG_MTD_NAND_MT5861)   	+= nand_vfy_driver.o

#Use Nand Common Driver End

# IF WE NOT USE Nand Common Driver
obj-$(CONFIG_MTD_NAND_MT5368)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5389)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5396)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5398)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5880)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5881)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5399)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5890)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5891)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5861)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5882)		+= mtk_nand.o mtdsdm.o
obj-$(CONFIG_MTD_NAND_MT5883)		+= mtk_nand.o mtdsdm.o


nand-objs := nand_base.o nand_bbt.o
