#ifndef VERSION_H
#define VERSION_H

#ifndef VERSION_STR_POSTFIX
#define VERSION_STR_POSTFIX " 20120927"
#endif /* VERSION_STR_POSTFIX */

#define VERSION_STR "0.8.x" VERSION_STR_POSTFIX

#endif /* VERSION_H */
