#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>
#

#snd-mtk-objs  := mtk.o
snd-mtk-objs  := alsa_card.o alsa_pcm.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_MTK) += snd-mtk.o
